### ISSUE TITLE
model comparison

### ISSUE THREAD

**Issue by PTWaade** [ilabcode/ActionModels.jl#116]
Need to save loglikelihoods - should be optional

**Comment by zeyus** [comment]
This is done with `@addlogprob!` right? It would also be possible to return an array (then use `generated_quantities()`)

I was thinking to avoid an if statement in the model code it could be wrapped in a function that is created at runtime (before model execution) and either does nothing, or updates the log likelihood if it is enabled?

**Comment by PTWaade** [comment]
This wpuld be the best model comparison metric:
https://python.arviz.org/en/latest/api/generated/arviz.psislw.html

But there is also WAIC
